/* ---------------- tiny CSV parser (handles quoted commas) ---------------- */
function parseCsv(text){
  const rows = [];
  let row = [], field = "", inQuotes = false;
  for (let i = 0; i < text.length; i++){
    const c = text[i], next = text[i+1];
    if (inQuotes){
      if (c === '"' && next === '"'){ field += '"'; i++; }
      else if (c === '"'){ inQuotes = false; }
      else field += c;
    } else {
      if (c === '"') inQuotes = true;
      else if (c === ','){ row.push(field); field = ""; }
      else if (c === '\r'){ /* skip */ }
      else if (c === '\n'){ row.push(field); rows.push(row); row = []; field = ""; }
      else field += c;
    }
  }
  if (field.length || row.length){ row.push(field); rows.push(row); }
  const clean = rows.filter(r => r.some(c => c.trim() !== ""));
  const header = clean[0].map(h => h.trim());
  return clean.slice(1).map(r => {
    const obj = {};
    header.forEach((h, i) => obj[h] = (r[i] ?? "").trim());
    return obj;
  });
}

function download(filename, content, mime){
  const blob = new Blob([content], { type: mime || "text/plain" });
  const a = document.createElement("a");
  a.href = URL.createObjectURL(blob);
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
}

function previewTable(rows, columns){
  if (!rows.length) return "<p class='hint'>No rows found.</p>";
  let html = "<table class='preview'><thead><tr>" + columns.map(c => `<th>${c}</th>`).join("") + "</tr></thead><tbody>";
  rows.slice(0, 6).forEach(r => {
    html += "<tr>" + columns.map(c => `<td>${(r[c] ?? "").toString().slice(0,60)}</td>`).join("") + "</tr>";
  });
  html += "</tbody></table>";
  if (rows.length > 6) html += `<p class="hint" style="margin-top:8px;">…and ${rows.length - 6} more row(s).</p>`;
  return html;
}

/* ---------------- 1. Students ---------------- */
let studentsData = null;
document.getElementById("studentsCsv").addEventListener("change", async (e) => {
  const file = e.target.files[0];
  if (!file) return;
  const rows = parseCsv(await file.text());
  studentsData = rows.map(r => ({ username: r.username, password: r.password, name: r.name || r.username }));
  document.getElementById("studentsBadge").textContent = `${studentsData.length} students loaded`;
  document.getElementById("studentsBadge").classList.add("ok");
  document.getElementById("studentsPreview").innerHTML = previewTable(rows, ["username","password","name"]);
  document.getElementById("studentsDownload").disabled = false;
});
document.getElementById("studentsDownload").addEventListener("click", () => {
  if (!studentsData) return;
  const js = `/* Auto-generated by admin.html from your students CSV. */\nconst STUDENTS = ${JSON.stringify(studentsData, null, 2)};\n`;
  download("students-data.js", js, "application/javascript");
});

/* ---------------- 2. Questions ---------------- */
let questionsData = null;
document.getElementById("questionsCsv").addEventListener("change", async (e) => {
  const file = e.target.files[0];
  if (!file) return;
  const rows = parseCsv(await file.text());
  questionsData = rows.map(r => ({
    q: r.question,
    options: { A: r.optionA, B: r.optionB, C: r.optionC, D: r.optionD },
    correct: (r.correct || "").trim().toUpperCase()
  }));
  document.getElementById("questionsBadge").textContent = `${questionsData.length} questions loaded`;
  document.getElementById("questionsBadge").classList.add("ok");
  document.getElementById("questionsPreview").innerHTML = previewTable(rows, ["question","optionA","optionB","optionC","optionD","correct"]);
  document.getElementById("questionsDownload").disabled = false;
});
document.getElementById("questionsDownload").addEventListener("click", () => {
  if (!questionsData) return;
  const js = `/* Auto-generated by admin.html from your questions CSV. */\nconst QUESTIONS = ${JSON.stringify(questionsData, null, 2)};\n`;
  download("questions-data.js", js, "application/javascript");
});

/* ---------------- 3. Rank list ---------------- */
let mergedResults = [];
document.getElementById("resultsCsv").addEventListener("change", async (e) => {
  const files = Array.from(e.target.files);
  mergedResults = [];
  for (const file of files){
    const rows = parseCsv(await file.text());
    rows.forEach(r => mergedResults.push(r));
  }
  mergedResults.sort((a, b) => (Number(b.score) - Number(a.score)) || (Number(a.elapsed_seconds) - Number(b.elapsed_seconds)));
  mergedResults.forEach((r, i) => r.rank = i + 1);
  document.getElementById("resultsBadge").textContent = `${files.length} file(s), ${mergedResults.length} result(s)`;
  document.getElementById("resultsBadge").classList.add("ok");
  document.getElementById("resultsPreview").innerHTML = previewTable(mergedResults, ["rank","username","name","score","total","violations","elapsed_seconds"]);
  document.getElementById("resultsDownload").disabled = mergedResults.length === 0;
});
document.getElementById("resultsDownload").addEventListener("click", () => {
  if (!mergedResults.length) return;
  const cols = ["rank","username","name","score","total","violations","submitted_at","elapsed_seconds"];
  const csv = [cols.join(",")].concat(
    mergedResults.map(r => cols.map(c => csvCell(r[c])).join(","))
  ).join("\n");
  download("rank_list.csv", csv, "text/csv");
});
function csvCell(v){
  const s = String(v ?? "");
  return /[",\n]/.test(s) ? `"${s.replace(/"/g,'""')}"` : s;
}
